### ISSUE TITLE
Incorrect geocoding for some points

### ISSUE THREAD

**Issue by themiurgo** [nestauk/museumsmap#1]
Some venues are incorrectly geocoded

**Comment by themiurgo** [comment]
This is partially fixed in 5958217.

**Comment by johnardavies** [comment]
The museum file has 1268 museums coded so looks as if it could be missing a few

**Comment by themiurgo** [comment]
@johnardavies Compared to which museum count?

**Comment by johnardavies** [comment]
Hope you're feeling better? 
From the accredited list on the Arts Council website I make it 1308

**Comment by themiurgo** [comment]
I'll send you a list of missing venues.
